### ISSUE TITLE
內容疑問

### ISSUE THREAD

**Issue by JIElite** [chenlifeng/F74058011_HW_Introduction-of-Spark#1]
請問你這些內容都是出自自己手打出來的心得嗎 ?

還是都是抄別人的 ?

demo code: https://www.ntu.edu.sg/home/ehchua/programming/sql/MySQL_Beginner.html
其他文章內容拿去 google 也都出自別人手中

**Comment by chenlifeng** [comment]
关于MySQL的各个知识点部分都是根据查找资料整理的（包括博客，wiki），而Demo code也是借鉴这篇文章，因为认为它的各个功能内容覆盖的比较全，（对不起我不知道Demo code需要自己写，我以为是自己找一下code然后执行一下尝试各个功能），然后使用心得我有附参考的博客链接，确实是我自己有使用MySQL但没有写具体的想法，想说从专业角度分析的话就参考一些评价的比较好的博客这样会显得给读者比较有可看性。
所以这个HW不是我一个字一个字手打的，是整理资料（我之前理解是关于这个工具的各个知识整理成报告，要是这样做违规了很抱歉，或者侵权需要附链接我可以补上各个blog链接TT）

**Comment by chenlifeng** [comment]
或者我可以重做这个repo
